# Generated by Django 3.2.7 on 2022-03-28 17:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0002_candidateapplied'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CandidateApplied',
            new_name='CandidatesApplied',
        ),
    ]
